export default {
  movies: document.querySelector('.movies__list'),
  modalMovie: document.querySelector('.modal__card'),
  searchForm: document.querySelector('.header__form'),
  watchedBtn: document.querySelector('.header__library-btn--watched'),
  queueBtn: document.querySelector('.header__library-btn--queue'),
  warningText: document.querySelector('.header__warning-search'),
  backdrop: document.querySelector('.backdrop'),
  modalClose: document.querySelector('.modal__button--close'),
  pagination: document.querySelector('.tui-pagination'),
  body: document.querySelector('body'),
  modalTrailer: document.querySelector('.modal-trailer'),
  backdropTrailer: document.querySelector('.backdrop-trailer'),
  closeBtn: document.querySelector('.modal-trailer__button--close'),
  modalTrailerIframe: document.querySelector('.modal-trailer-iframe-container'),
  myLibraryBtn: document.querySelector('.header__link--my-library'),
  myLibraryWrap: document.querySelector('.library__wrap'),
  googleSignUp: document.getElementById('googleSignUp'),
  googleSignOut: document.getElementById('googleSignOut'),
  myLibrary: document.querySelector('.header__link--library'),
  googleSignOutFromLibrary: document.getElementById('libraryGoogleSignOut'),
  languageSelectBtn: document.querySelector('.language-btn'),
  themeSwitcher: document.querySelector('.theme-switcher input'),
  backdropDev: document.querySelector('.backdrop_dev'),
  closeBtnDev: document.querySelector('.modal_dev_btn--close '),
  filterGenreBtn: document.querySelector('[data-action="genres"]'),
  filterYearBtn: document.querySelector('[data-action="years"]'),
  btnUp: document.querySelector('.btn-up'),
  backdropDevs: document.querySelector('.backdrop_dev'),
  clsBtnModalDev: document.querySelector('.modal_dev_btn--close'),
  openBtnModalDev: document.querySelector('.footer__link'),
};
